<?php
return array(
    
    "router"=>array(
        "routes"=>array(
            "huser"=>array(
                "type"=>"Segment",
                "options"=>array(
                    "route"=>"/huser[/][:action].html",
                    "constraints"=>array(
                        "action"=>"[a-zA-Z0-9][a-zA-Z0-9_-]*",  
                    ),
                    "defaults"=>array(
                        "__NAMESPACE__"=>"Huser\Controller",
                        "controller"=>"User",
                        "action"=>"register"
                    )
                )
            ),
            "huser-center"=>array(
                "type"=>"Segment",
                "options"=>array(
                    "route"=>"/user-center[/:action].html",
                    "defaults"=>array(
                       "__NAMESPACE__"=>"Huser\Controller",
                        "controller"=>"HuserController",
                        "action"=>"index"
                    )
                )
            ),
        )  
    ),
    "view_manager"=>array(
        "template_path_stack"=>array(
            __DIR__."/../view",
        ),
        "template_map"=>array(
            "huser-layout"=>__DIR__."/../view/layout/huser-layout.phtml"
        )
    ),
    "h_user"=>array(
        "disabled_register"=>true,
        "disabled_login"=>false,
    ),
    "service_manager"=>array(
        "factories"=>array(
            'UserModuleOptions'=>"Huser\Service\Factory\UserModuleOptions"
        )
    )
);